/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthenticationInput { 'password' : string, 'email' : string }
export interface Document {
  'id' : string,
  'engagementId' : EngagementId,
  'name' : string,
  'createdAt' : Time,
  'size' : bigint,
  'storageLocation' : ExternalBlob,
  'docType' : DocumentType,
}
export type DocumentType = { 'pdf' : null } |
  { 'image' : null };
export interface Engagement {
  'id' : EngagementId,
  'financialYear' : bigint,
  'clientName' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'auditEndDate' : Time,
  'engagementType' : EngagementType,
  'updatedAt' : Time,
  'finalized' : boolean,
  'materialityAmount' : number,
  'auditStartDate' : Time,
}
export type EngagementId = bigint;
export type EngagementType = { 'internal' : null } |
  { 'external' : null };
export type ExternalBlob = Uint8Array;
export interface Issue {
  'id' : IssueId,
  'status' : IssueStatus,
  'engagementId' : EngagementId,
  'owner' : Principal,
  'recommendations' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'monetaryImpact' : number,
  'managementResponse' : string,
  'riskLevel' : RiskLevel,
}
export type IssueId = bigint;
export type IssueStatus = { 'closed' : null } |
  { 'open' : null };
export interface OpeningBalanceTest {
  'id' : OpeningBalanceTestId,
  'engagementId' : EngagementId,
  'owner' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'accountName' : string,
  'notes' : string,
  'priorYearClosingBalance' : number,
  'currentYearOpeningBalance' : number,
}
export type OpeningBalanceTestId = bigint;
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Section {
  'id' : SectionId,
  'engagementId' : EngagementId,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'isCustom' : boolean,
  'formula' : string,
}
export type SectionId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workpaper {
  'id' : WorkpaperId,
  'documentIds' : Array<string>,
  'riskRating' : RiskLevel,
  'auditObjective' : string,
  'sampleDetails' : string,
  'createdAt' : Time,
  'conclusion' : string,
  'proceduresPerformed' : string,
  'generalLedgerTotal' : number,
  'updatedAt' : Time,
  'sectionId' : SectionId,
  'evidenceDescription' : string,
  'findings' : string,
  'trialBalanceTotal' : number,
}
export type WorkpaperId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSection' : ActorMethod<[Section], undefined>,
  'deleteEngagement' : ActorMethod<[EngagementId], undefined>,
  'deleteIssue' : ActorMethod<[IssueId], undefined>,
  'deleteOpeningBalanceTest' : ActorMethod<[OpeningBalanceTestId], undefined>,
  'deleteSection' : ActorMethod<[SectionId], undefined>,
  'generateReport' : ActorMethod<[EngagementId], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<
    [],
    {
      'totalEngagements' : bigint,
      'highRiskIssues' : bigint,
      'openIssues' : bigint,
    }
  >,
  'getDocument' : ActorMethod<[string], Document>,
  'getEngagementDetails' : ActorMethod<[EngagementId], Engagement>,
  'getEngagements' : ActorMethod<[], Array<Engagement>>,
  'getIssues' : ActorMethod<[[] | [EngagementId]], Array<Issue>>,
  'getOpeningBalanceTests' : ActorMethod<
    [EngagementId],
    Array<OpeningBalanceTest>
  >,
  'getSections' : ActorMethod<[EngagementId], Array<Section>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkpapers' : ActorMethod<[SectionId], Array<Workpaper>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[AuthenticationInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDocument' : ActorMethod<[Document], undefined>,
  'saveEngagement' : ActorMethod<
    [Engagement, Array<Section>, Array<Workpaper>, Array<Issue>],
    undefined
  >,
  'saveIssue' : ActorMethod<[Issue], undefined>,
  'saveOpeningBalanceTest' : ActorMethod<[OpeningBalanceTest], undefined>,
  'saveWorkpaper' : ActorMethod<[Workpaper], undefined>,
  'updateEngagement' : ActorMethod<[EngagementId, Engagement], undefined>,
  'updateIssue' : ActorMethod<[IssueId, Issue], undefined>,
  'updateOpeningBalanceTest' : ActorMethod<
    [OpeningBalanceTestId, OpeningBalanceTest],
    undefined
  >,
  'updateSection' : ActorMethod<[SectionId, { 'formula' : string }], undefined>,
  'updateWorkpaper' : ActorMethod<[WorkpaperId, Workpaper], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];