/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SectionId = IDL.Nat;
export const EngagementId = IDL.Nat;
export const Time = IDL.Int;
export const Section = IDL.Record({
  'id' : SectionId,
  'engagementId' : EngagementId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'isCustom' : IDL.Bool,
  'formula' : IDL.Text,
});
export const IssueId = IDL.Nat;
export const OpeningBalanceTestId = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentType = IDL.Variant({
  'pdf' : IDL.Null,
  'image' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'engagementId' : EngagementId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'storageLocation' : ExternalBlob,
  'docType' : DocumentType,
});
export const EngagementType = IDL.Variant({
  'internal' : IDL.Null,
  'external' : IDL.Null,
});
export const Engagement = IDL.Record({
  'id' : EngagementId,
  'financialYear' : IDL.Nat,
  'clientName' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'auditEndDate' : Time,
  'engagementType' : EngagementType,
  'updatedAt' : Time,
  'finalized' : IDL.Bool,
  'materialityAmount' : IDL.Float64,
  'auditStartDate' : Time,
});
export const IssueStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Issue = IDL.Record({
  'id' : IssueId,
  'status' : IssueStatus,
  'engagementId' : EngagementId,
  'owner' : IDL.Principal,
  'recommendations' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'monetaryImpact' : IDL.Float64,
  'managementResponse' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const OpeningBalanceTest = IDL.Record({
  'id' : OpeningBalanceTestId,
  'engagementId' : EngagementId,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'accountName' : IDL.Text,
  'notes' : IDL.Text,
  'priorYearClosingBalance' : IDL.Float64,
  'currentYearOpeningBalance' : IDL.Float64,
});
export const WorkpaperId = IDL.Nat;
export const Workpaper = IDL.Record({
  'id' : WorkpaperId,
  'documentIds' : IDL.Vec(IDL.Text),
  'riskRating' : RiskLevel,
  'auditObjective' : IDL.Text,
  'sampleDetails' : IDL.Text,
  'createdAt' : Time,
  'conclusion' : IDL.Text,
  'proceduresPerformed' : IDL.Text,
  'generalLedgerTotal' : IDL.Float64,
  'updatedAt' : Time,
  'sectionId' : SectionId,
  'evidenceDescription' : IDL.Text,
  'findings' : IDL.Text,
  'trialBalanceTotal' : IDL.Float64,
});
export const AuthenticationInput = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSection' : IDL.Func([Section], [], []),
  'deleteEngagement' : IDL.Func([EngagementId], [], []),
  'deleteIssue' : IDL.Func([IssueId], [], []),
  'deleteOpeningBalanceTest' : IDL.Func([OpeningBalanceTestId], [], []),
  'deleteSection' : IDL.Func([SectionId], [], []),
  'generateReport' : IDL.Func([EngagementId], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEngagements' : IDL.Nat,
          'highRiskIssues' : IDL.Nat,
          'openIssues' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
  'getEngagementDetails' : IDL.Func([EngagementId], [Engagement], ['query']),
  'getEngagements' : IDL.Func([], [IDL.Vec(Engagement)], ['query']),
  'getIssues' : IDL.Func([IDL.Opt(EngagementId)], [IDL.Vec(Issue)], ['query']),
  'getOpeningBalanceTests' : IDL.Func(
      [EngagementId],
      [IDL.Vec(OpeningBalanceTest)],
      ['query'],
    ),
  'getSections' : IDL.Func([EngagementId], [IDL.Vec(Section)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkpapers' : IDL.Func([SectionId], [IDL.Vec(Workpaper)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([AuthenticationInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDocument' : IDL.Func([Document], [], []),
  'saveEngagement' : IDL.Func(
      [Engagement, IDL.Vec(Section), IDL.Vec(Workpaper), IDL.Vec(Issue)],
      [],
      [],
    ),
  'saveIssue' : IDL.Func([Issue], [], []),
  'saveOpeningBalanceTest' : IDL.Func([OpeningBalanceTest], [], []),
  'saveWorkpaper' : IDL.Func([Workpaper], [], []),
  'updateEngagement' : IDL.Func([EngagementId, Engagement], [], []),
  'updateIssue' : IDL.Func([IssueId, Issue], [], []),
  'updateOpeningBalanceTest' : IDL.Func(
      [OpeningBalanceTestId, OpeningBalanceTest],
      [],
      [],
    ),
  'updateSection' : IDL.Func(
      [SectionId, IDL.Record({ 'formula' : IDL.Text })],
      [],
      [],
    ),
  'updateWorkpaper' : IDL.Func([WorkpaperId, Workpaper], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SectionId = IDL.Nat;
  const EngagementId = IDL.Nat;
  const Time = IDL.Int;
  const Section = IDL.Record({
    'id' : SectionId,
    'engagementId' : EngagementId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'isCustom' : IDL.Bool,
    'formula' : IDL.Text,
  });
  const IssueId = IDL.Nat;
  const OpeningBalanceTestId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentType = IDL.Variant({ 'pdf' : IDL.Null, 'image' : IDL.Null });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'engagementId' : EngagementId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'storageLocation' : ExternalBlob,
    'docType' : DocumentType,
  });
  const EngagementType = IDL.Variant({
    'internal' : IDL.Null,
    'external' : IDL.Null,
  });
  const Engagement = IDL.Record({
    'id' : EngagementId,
    'financialYear' : IDL.Nat,
    'clientName' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'auditEndDate' : Time,
    'engagementType' : EngagementType,
    'updatedAt' : Time,
    'finalized' : IDL.Bool,
    'materialityAmount' : IDL.Float64,
    'auditStartDate' : Time,
  });
  const IssueStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Issue = IDL.Record({
    'id' : IssueId,
    'status' : IssueStatus,
    'engagementId' : EngagementId,
    'owner' : IDL.Principal,
    'recommendations' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'monetaryImpact' : IDL.Float64,
    'managementResponse' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const OpeningBalanceTest = IDL.Record({
    'id' : OpeningBalanceTestId,
    'engagementId' : EngagementId,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'accountName' : IDL.Text,
    'notes' : IDL.Text,
    'priorYearClosingBalance' : IDL.Float64,
    'currentYearOpeningBalance' : IDL.Float64,
  });
  const WorkpaperId = IDL.Nat;
  const Workpaper = IDL.Record({
    'id' : WorkpaperId,
    'documentIds' : IDL.Vec(IDL.Text),
    'riskRating' : RiskLevel,
    'auditObjective' : IDL.Text,
    'sampleDetails' : IDL.Text,
    'createdAt' : Time,
    'conclusion' : IDL.Text,
    'proceduresPerformed' : IDL.Text,
    'generalLedgerTotal' : IDL.Float64,
    'updatedAt' : Time,
    'sectionId' : SectionId,
    'evidenceDescription' : IDL.Text,
    'findings' : IDL.Text,
    'trialBalanceTotal' : IDL.Float64,
  });
  const AuthenticationInput = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSection' : IDL.Func([Section], [], []),
    'deleteEngagement' : IDL.Func([EngagementId], [], []),
    'deleteIssue' : IDL.Func([IssueId], [], []),
    'deleteOpeningBalanceTest' : IDL.Func([OpeningBalanceTestId], [], []),
    'deleteSection' : IDL.Func([SectionId], [], []),
    'generateReport' : IDL.Func([EngagementId], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEngagements' : IDL.Nat,
            'highRiskIssues' : IDL.Nat,
            'openIssues' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDocument' : IDL.Func([IDL.Text], [Document], ['query']),
    'getEngagementDetails' : IDL.Func([EngagementId], [Engagement], ['query']),
    'getEngagements' : IDL.Func([], [IDL.Vec(Engagement)], ['query']),
    'getIssues' : IDL.Func(
        [IDL.Opt(EngagementId)],
        [IDL.Vec(Issue)],
        ['query'],
      ),
    'getOpeningBalanceTests' : IDL.Func(
        [EngagementId],
        [IDL.Vec(OpeningBalanceTest)],
        ['query'],
      ),
    'getSections' : IDL.Func([EngagementId], [IDL.Vec(Section)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkpapers' : IDL.Func([SectionId], [IDL.Vec(Workpaper)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([AuthenticationInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDocument' : IDL.Func([Document], [], []),
    'saveEngagement' : IDL.Func(
        [Engagement, IDL.Vec(Section), IDL.Vec(Workpaper), IDL.Vec(Issue)],
        [],
        [],
      ),
    'saveIssue' : IDL.Func([Issue], [], []),
    'saveOpeningBalanceTest' : IDL.Func([OpeningBalanceTest], [], []),
    'saveWorkpaper' : IDL.Func([Workpaper], [], []),
    'updateEngagement' : IDL.Func([EngagementId, Engagement], [], []),
    'updateIssue' : IDL.Func([IssueId, Issue], [], []),
    'updateOpeningBalanceTest' : IDL.Func(
        [OpeningBalanceTestId, OpeningBalanceTest],
        [],
        [],
      ),
    'updateSection' : IDL.Func(
        [SectionId, IDL.Record({ 'formula' : IDL.Text })],
        [],
        [],
      ),
    'updateWorkpaper' : IDL.Func([WorkpaperId, Workpaper], [], []),
  });
};

export const init = ({ IDL }) => { return []; };