/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type OpeningBalanceTestId = bigint;
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Issue {
    id: IssueId;
    status: IssueStatus;
    engagementId: EngagementId;
    owner: Principal;
    recommendations: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    monetaryImpact: number;
    managementResponse: string;
    riskLevel: RiskLevel;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type EngagementId = bigint;
export interface Document {
    id: string;
    engagementId: EngagementId;
    name: string;
    createdAt: Time;
    size: bigint;
    storageLocation: ExternalBlob;
    docType: DocumentType;
}
export interface OpeningBalanceTest {
    id: OpeningBalanceTestId;
    engagementId: EngagementId;
    owner: Principal;
    createdAt: Time;
    updatedAt: Time;
    accountName: string;
    notes: string;
    priorYearClosingBalance: number;
    currentYearOpeningBalance: number;
}
export interface Engagement {
    id: EngagementId;
    financialYear: bigint;
    clientName: string;
    owner: Principal;
    createdAt: Time;
    auditEndDate: Time;
    engagementType: EngagementType;
    updatedAt: Time;
    finalized: boolean;
    materialityAmount: number;
    auditStartDate: Time;
}
export interface Workpaper {
    id: WorkpaperId;
    documentIds: Array<string>;
    riskRating: RiskLevel;
    auditObjective: string;
    sampleDetails: string;
    createdAt: Time;
    conclusion: string;
    proceduresPerformed: string;
    generalLedgerTotal: number;
    updatedAt: Time;
    sectionId: SectionId;
    evidenceDescription: string;
    findings: string;
    trialBalanceTotal: number;
}
export type WorkpaperId = bigint;
export interface AuthenticationInput {
    password: string;
    email: string;
}
export interface Section {
    id: SectionId;
    engagementId: EngagementId;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    isCustom: boolean;
    formula: string;
}
export type IssueId = bigint;
export type SectionId = bigint;
export interface UserProfile {
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum DocumentType {
    pdf = "pdf",
    image = "image"
}
export enum EngagementType {
    internal = "internal",
    external = "external"
}
export enum IssueStatus {
    closed = "closed",
    open = "open"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSection(section: Section): Promise<void>;
    deleteEngagement(engagementId: EngagementId): Promise<void>;
    deleteIssue(issueId: IssueId): Promise<void>;
    deleteOpeningBalanceTest(testId: OpeningBalanceTestId): Promise<void>;
    deleteSection(sectionId: SectionId): Promise<void>;
    generateReport(engagementId: EngagementId): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardData(): Promise<{
        totalEngagements: bigint;
        highRiskIssues: bigint;
        openIssues: bigint;
    }>;
    getDocument(documentId: string): Promise<Document>;
    getEngagementDetails(engagementId: EngagementId): Promise<Engagement>;
    getEngagements(): Promise<Array<Engagement>>;
    getIssues(engagementId: EngagementId | null): Promise<Array<Issue>>;
    getOpeningBalanceTests(engagementId: EngagementId): Promise<Array<OpeningBalanceTest>>;
    getSections(engagementId: EngagementId): Promise<Array<Section>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkpapers(sectionId: SectionId): Promise<Array<Workpaper>>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(authData: AuthenticationInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDocument(document: Document): Promise<void>;
    saveEngagement(engagement: Engagement, _sections: Array<Section>, _workpapers: Array<Workpaper>, _issues: Array<Issue>): Promise<void>;
    saveIssue(issue: Issue): Promise<void>;
    saveOpeningBalanceTest(test: OpeningBalanceTest): Promise<void>;
    saveWorkpaper(workpaper: Workpaper): Promise<void>;
    updateEngagement(engagementId: EngagementId, engagement: Engagement): Promise<void>;
    updateIssue(issueId: IssueId, issue: Issue): Promise<void>;
    updateOpeningBalanceTest(testId: OpeningBalanceTestId, test: OpeningBalanceTest): Promise<void>;
    updateSection(sectionId: SectionId, updatedFields: {
        formula: string;
    }): Promise<void>;
    updateWorkpaper(workpaperId: WorkpaperId, workpaper: Workpaper): Promise<void>;
}
import type { Document as _Document, DocumentType as _DocumentType, Engagement as _Engagement, EngagementId as _EngagementId, EngagementType as _EngagementType, ExternalBlob as _ExternalBlob, Issue as _Issue, IssueId as _IssueId, IssueStatus as _IssueStatus, RiskLevel as _RiskLevel, SectionId as _SectionId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Workpaper as _Workpaper, WorkpaperId as _WorkpaperId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSection(arg0: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSection(arg0);
            return result;
        }
    }
    async deleteEngagement(arg0: EngagementId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEngagement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEngagement(arg0);
            return result;
        }
    }
    async deleteIssue(arg0: IssueId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIssue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIssue(arg0);
            return result;
        }
    }
    async deleteOpeningBalanceTest(arg0: OpeningBalanceTestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOpeningBalanceTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOpeningBalanceTest(arg0);
            return result;
        }
    }
    async deleteSection(arg0: SectionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0);
            return result;
        }
    }
    async generateReport(arg0: EngagementId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(): Promise<{
        totalEngagements: bigint;
        highRiskIssues: bigint;
        openIssues: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return result;
        }
    }
    async getDocument(arg0: string): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_Document_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_Document_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEngagementDetails(arg0: EngagementId): Promise<Engagement> {
        if (this.processError) {
            try {
                const result = await this.actor.getEngagementDetails(arg0);
                return from_candid_Engagement_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEngagementDetails(arg0);
            return from_candid_Engagement_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEngagements(): Promise<Array<Engagement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEngagements();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEngagements();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIssues(arg0: EngagementId | null): Promise<Array<Issue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIssues(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIssues(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpeningBalanceTests(arg0: EngagementId): Promise<Array<OpeningBalanceTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpeningBalanceTests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpeningBalanceTests(arg0);
            return result;
        }
    }
    async getSections(arg0: EngagementId): Promise<Array<Section>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSections(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkpapers(arg0: SectionId): Promise<Array<Workpaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkpapers(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkpapers(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: AuthenticationInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDocument(arg0: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDocument(await to_candid_Document_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDocument(await to_candid_Document_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveEngagement(arg0: Engagement, arg1: Array<Section>, arg2: Array<Workpaper>, arg3: Array<Issue>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEngagement(to_candid_Engagement_n39(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_vec_n43(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n48(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEngagement(to_candid_Engagement_n39(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_vec_n43(this._uploadFile, this._downloadFile, arg2), to_candid_vec_n48(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async saveIssue(arg0: Issue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIssue(to_candid_Issue_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIssue(to_candid_Issue_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOpeningBalanceTest(arg0: OpeningBalanceTest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOpeningBalanceTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOpeningBalanceTest(arg0);
            return result;
        }
    }
    async saveWorkpaper(arg0: Workpaper): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWorkpaper(to_candid_Workpaper_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWorkpaper(to_candid_Workpaper_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEngagement(arg0: EngagementId, arg1: Engagement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEngagement(arg0, to_candid_Engagement_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEngagement(arg0, to_candid_Engagement_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateIssue(arg0: IssueId, arg1: Issue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIssue(arg0, to_candid_Issue_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIssue(arg0, to_candid_Issue_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOpeningBalanceTest(arg0: OpeningBalanceTestId, arg1: OpeningBalanceTest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpeningBalanceTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpeningBalanceTest(arg0, arg1);
            return result;
        }
    }
    async updateSection(arg0: SectionId, arg1: {
        formula: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(arg0, arg1);
            return result;
        }
    }
    async updateWorkpaper(arg0: WorkpaperId, arg1: Workpaper): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkpaper(arg0, to_candid_Workpaper_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkpaper(arg0, to_candid_Workpaper_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DocumentType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EngagementType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EngagementType): EngagementType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Engagement_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Engagement): Engagement {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_IssueStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueStatus): IssueStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Issue_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Issue): Issue {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Workpaper_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Workpaper): Workpaper {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    engagementId: _EngagementId;
    name: string;
    createdAt: _Time;
    size: bigint;
    storageLocation: _ExternalBlob;
    docType: _DocumentType;
}): Promise<{
    id: string;
    engagementId: EngagementId;
    name: string;
    createdAt: Time;
    size: bigint;
    storageLocation: ExternalBlob;
    docType: DocumentType;
}> {
    return {
        id: value.id,
        engagementId: value.engagementId,
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        storageLocation: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.storageLocation),
        docType: from_candid_DocumentType_n16(_uploadFile, _downloadFile, value.docType)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EngagementId;
    financialYear: bigint;
    clientName: string;
    owner: Principal;
    createdAt: _Time;
    auditEndDate: _Time;
    engagementType: _EngagementType;
    updatedAt: _Time;
    finalized: boolean;
    materialityAmount: number;
    auditStartDate: _Time;
}): {
    id: EngagementId;
    financialYear: bigint;
    clientName: string;
    owner: Principal;
    createdAt: Time;
    auditEndDate: Time;
    engagementType: EngagementType;
    updatedAt: Time;
    finalized: boolean;
    materialityAmount: number;
    auditStartDate: Time;
} {
    return {
        id: value.id,
        financialYear: value.financialYear,
        clientName: value.clientName,
        owner: value.owner,
        createdAt: value.createdAt,
        auditEndDate: value.auditEndDate,
        engagementType: from_candid_EngagementType_n20(_uploadFile, _downloadFile, value.engagementType),
        updatedAt: value.updatedAt,
        finalized: value.finalized,
        materialityAmount: value.materialityAmount,
        auditStartDate: value.auditStartDate
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IssueId;
    status: _IssueStatus;
    engagementId: _EngagementId;
    owner: Principal;
    recommendations: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    monetaryImpact: number;
    managementResponse: string;
    riskLevel: _RiskLevel;
}): {
    id: IssueId;
    status: IssueStatus;
    engagementId: EngagementId;
    owner: Principal;
    recommendations: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    monetaryImpact: number;
    managementResponse: string;
    riskLevel: RiskLevel;
} {
    return {
        id: value.id,
        status: from_candid_IssueStatus_n27(_uploadFile, _downloadFile, value.status),
        engagementId: value.engagementId,
        owner: value.owner,
        recommendations: value.recommendations,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        monetaryImpact: value.monetaryImpact,
        managementResponse: value.managementResponse,
        riskLevel: from_candid_RiskLevel_n29(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkpaperId;
    documentIds: Array<string>;
    riskRating: _RiskLevel;
    auditObjective: string;
    sampleDetails: string;
    createdAt: _Time;
    conclusion: string;
    proceduresPerformed: string;
    generalLedgerTotal: number;
    updatedAt: _Time;
    sectionId: _SectionId;
    evidenceDescription: string;
    findings: string;
    trialBalanceTotal: number;
}): {
    id: WorkpaperId;
    documentIds: Array<string>;
    riskRating: RiskLevel;
    auditObjective: string;
    sampleDetails: string;
    createdAt: Time;
    conclusion: string;
    proceduresPerformed: string;
    generalLedgerTotal: number;
    updatedAt: Time;
    sectionId: SectionId;
    evidenceDescription: string;
    findings: string;
    trialBalanceTotal: number;
} {
    return {
        id: value.id,
        documentIds: value.documentIds,
        riskRating: from_candid_RiskLevel_n29(_uploadFile, _downloadFile, value.riskRating),
        auditObjective: value.auditObjective,
        sampleDetails: value.sampleDetails,
        createdAt: value.createdAt,
        conclusion: value.conclusion,
        proceduresPerformed: value.proceduresPerformed,
        generalLedgerTotal: value.generalLedgerTotal,
        updatedAt: value.updatedAt,
        sectionId: value.sectionId,
        evidenceDescription: value.evidenceDescription,
        findings: value.findings,
        trialBalanceTotal: value.trialBalanceTotal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    image: null;
}): DocumentType {
    return "pdf" in value ? DocumentType.pdf : "image" in value ? DocumentType.image : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internal: null;
} | {
    external: null;
}): EngagementType {
    return "internal" in value ? EngagementType.internal : "external" in value ? EngagementType.external : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): IssueStatus {
    return "closed" in value ? IssueStatus.closed : "open" in value ? IssueStatus.open : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Engagement>): Array<Engagement> {
    return value.map((x)=>from_candid_Engagement_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Issue>): Array<Issue> {
    return value.map((x)=>from_candid_Issue_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Workpaper>): Array<Workpaper> {
    return value.map((x)=>from_candid_Workpaper_n32(_uploadFile, _downloadFile, x));
}
function to_candid_DocumentType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_Document_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): Promise<_Document> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_EngagementType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementType): _EngagementType {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Engagement_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Engagement): _Engagement {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IssueStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueStatus): _IssueStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Issue_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Issue): _Issue {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_RiskLevel_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): _RiskLevel {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Workpaper_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Workpaper): _Workpaper {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementId | null): [] | [_EngagementId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    engagementId: EngagementId;
    name: string;
    createdAt: Time;
    size: bigint;
    storageLocation: ExternalBlob;
    docType: DocumentType;
}): Promise<{
    id: string;
    engagementId: _EngagementId;
    name: string;
    createdAt: _Time;
    size: bigint;
    storageLocation: _ExternalBlob;
    docType: _DocumentType;
}> {
    return {
        id: value.id,
        engagementId: value.engagementId,
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        storageLocation: await to_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.storageLocation),
        docType: to_candid_DocumentType_n37(_uploadFile, _downloadFile, value.docType)
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EngagementId;
    financialYear: bigint;
    clientName: string;
    owner: Principal;
    createdAt: Time;
    auditEndDate: Time;
    engagementType: EngagementType;
    updatedAt: Time;
    finalized: boolean;
    materialityAmount: number;
    auditStartDate: Time;
}): {
    id: _EngagementId;
    financialYear: bigint;
    clientName: string;
    owner: Principal;
    createdAt: _Time;
    auditEndDate: _Time;
    engagementType: _EngagementType;
    updatedAt: _Time;
    finalized: boolean;
    materialityAmount: number;
    auditStartDate: _Time;
} {
    return {
        id: value.id,
        financialYear: value.financialYear,
        clientName: value.clientName,
        owner: value.owner,
        createdAt: value.createdAt,
        auditEndDate: value.auditEndDate,
        engagementType: to_candid_EngagementType_n41(_uploadFile, _downloadFile, value.engagementType),
        updatedAt: value.updatedAt,
        finalized: value.finalized,
        materialityAmount: value.materialityAmount,
        auditStartDate: value.auditStartDate
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: WorkpaperId;
    documentIds: Array<string>;
    riskRating: RiskLevel;
    auditObjective: string;
    sampleDetails: string;
    createdAt: Time;
    conclusion: string;
    proceduresPerformed: string;
    generalLedgerTotal: number;
    updatedAt: Time;
    sectionId: SectionId;
    evidenceDescription: string;
    findings: string;
    trialBalanceTotal: number;
}): {
    id: _WorkpaperId;
    documentIds: Array<string>;
    riskRating: _RiskLevel;
    auditObjective: string;
    sampleDetails: string;
    createdAt: _Time;
    conclusion: string;
    proceduresPerformed: string;
    generalLedgerTotal: number;
    updatedAt: _Time;
    sectionId: _SectionId;
    evidenceDescription: string;
    findings: string;
    trialBalanceTotal: number;
} {
    return {
        id: value.id,
        documentIds: value.documentIds,
        riskRating: to_candid_RiskLevel_n46(_uploadFile, _downloadFile, value.riskRating),
        auditObjective: value.auditObjective,
        sampleDetails: value.sampleDetails,
        createdAt: value.createdAt,
        conclusion: value.conclusion,
        proceduresPerformed: value.proceduresPerformed,
        generalLedgerTotal: value.generalLedgerTotal,
        updatedAt: value.updatedAt,
        sectionId: value.sectionId,
        evidenceDescription: value.evidenceDescription,
        findings: value.findings,
        trialBalanceTotal: value.trialBalanceTotal
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: IssueId;
    status: IssueStatus;
    engagementId: EngagementId;
    owner: Principal;
    recommendations: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    monetaryImpact: number;
    managementResponse: string;
    riskLevel: RiskLevel;
}): {
    id: _IssueId;
    status: _IssueStatus;
    engagementId: _EngagementId;
    owner: Principal;
    recommendations: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    monetaryImpact: number;
    managementResponse: string;
    riskLevel: _RiskLevel;
} {
    return {
        id: value.id,
        status: to_candid_IssueStatus_n51(_uploadFile, _downloadFile, value.status),
        engagementId: value.engagementId,
        owner: value.owner,
        recommendations: value.recommendations,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        monetaryImpact: value.monetaryImpact,
        managementResponse: value.managementResponse,
        riskLevel: to_candid_RiskLevel_n46(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    pdf: null;
} | {
    image: null;
} {
    return value == DocumentType.pdf ? {
        pdf: null
    } : value == DocumentType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementType): {
    internal: null;
} | {
    external: null;
} {
    return value == EngagementType.internal ? {
        internal: null
    } : value == EngagementType.external ? {
        external: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == RiskLevel.low ? {
        low: null
    } : value == RiskLevel.high ? {
        high: null
    } : value == RiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueStatus): {
    closed: null;
} | {
    open: null;
} {
    return value == IssueStatus.closed ? {
        closed: null
    } : value == IssueStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Workpaper>): Array<_Workpaper> {
    return value.map((x)=>to_candid_Workpaper_n44(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Issue>): Array<_Issue> {
    return value.map((x)=>to_candid_Issue_n49(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
